# -*- coding: utf-8 -*-
"""FAQs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbE5rCijc58MZ0UqNOMcN4Nj2QfDGiHZ
"""

!pip install nltk scikit-learn

import nltk
import string

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('punkt')
nltk.download('stopwords')

faqs = {

    "How to reset password?":
    "Click on forgot password option to reset your password.",


    "What is your refund policy?":
    "Refund is available within 7 days after purchase.",


    "What are your office timings?":
    "Our office is open from 9 AM to 5 PM.",


    "How can I contact support?":
    "You can contact support through email or phone.",


    "Where is your office located?":
    "Our office is located in Lahore, Pakistan.",


    "Do you provide home delivery?":
    "Yes, we provide home delivery in selected cities.",


    "How long does delivery take?":
    "Delivery usually takes 3 to 5 working days.",


    "Can I change my order after placing it?":
    "Yes, you can change your order within 2 hours.",


    "What payment methods do you accept?":
    "We accept JazzCash, EasyPaisa, debit cards, and credit cards.",


    "Is cash on delivery available?":
    "Yes, cash on delivery is available in most cities.",


    "How can I track my order?":
    "You can track your order using the tracking ID sent to your email.",


    "Do you offer discounts for students?":
    "Yes, we offer special discounts for students.",


    "Can I cancel my order?":
    "Yes, orders can be canceled before shipment.",


    "Do you have a mobile app?":
    "Yes, our mobile app is available on Android and iOS.",


    "How can I create an account?":
    "Click on sign up and fill in your details to create an account.",


    "What should I do if I forget my password?":
    "Use the forgot password option to create a new password.",


    "Are your services available 24/7?":
    "Yes, our online services are available 24 hours a day.",


    "How can I update my profile information?":
    "Go to account settings and update your profile information.",


    "Do you provide international shipping?":
    "Yes, international shipping is available for selected countries.",


    "How can I delete my account?":
    "Contact customer support to permanently delete your account."
}

"""italicized text"""

def preprocess_text(text):

    # lowercase
    text = text.lower()

    # punctuation remove
    text = text.translate(str.maketrans('', '', string.punctuation))

    # tokenize
    words = word_tokenize(text)

    # stopwords remove
    stop_words = set(stopwords.words('english'))

    filtered_words = [
        word for word in words
        if word not in stop_words
    ]

    return " ".join(filtered_words)

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

faq_questions = list(faqs.keys())

processed_questions = [
    preprocess_text(q)
    for q in faq_questions
]

print(processed_questions)

vectorizer = TfidfVectorizer()

faq_vectors = vectorizer.fit_transform(processed_questions)

def chatbot(user_question):

    # preprocess user question
    processed_input = preprocess_text(user_question)

    # convert into vector
    user_vector = vectorizer.transform([processed_input])

    # cosine similarity
    similarity = cosine_similarity(user_vector, faq_vectors)

    # best match index
    best_match_index = similarity.argmax()

    # similarity score
    best_score = similarity[0][best_match_index]

    # threshold
    if best_score < 0.2:
        return "Sorry, I could not understand your question."

    # matched question
    matched_question = faq_questions[best_match_index]

    # return answer
    return faqs[matched_question]

question = input("Ask a question: ")

response = chatbot(question)

print("\nChatbot:", response)

